[package]
name = "puyo-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
puyo-core = { path = "../puyo-core" }
puyo-player = { path = "../puyo-player", features = ["nn"] }
puyo-nn = { path = "../puyo-nn" }
burn = { version = "0.19", default-features = false, features = ["ndarray"] }
wasm-bindgen = "0.2"
