[package]
name = "puyo-player"
version = "0.1.0"
edition = "2021"

[features]
default = []
nn = ["az-framework/nn", "puyo-nn", "burn"]
cuda = ["nn", "burn/cuda"]

[dependencies]
az-framework = { path = "../../az-framework" }
puyo-core = { path = "../puyo-core" }
puyo-nn = { path = "../puyo-nn", optional = true }
burn = { version = "0.19", default-features = false, features = ["ndarray"], optional = true }
